### ISSUE TITLE
无法clone代码

### ISSUE THREAD

**Issue by panyis** [alibaba/intelligent-test-platform#1]
“http://gitlab.alibaba-inc.com/engine-test-platform/markov_open”连接访问失败，无法clone代码，这个是公司内网的地址？

**Comment by blacklee123** [comment]
你直接clone本项目就行了

**Comment by emmalovestudy** [comment]
eclipse可以吗？

**Comment by anszhao** [comment]
> eclipse可以吗？

可以的，亲，只要eclipse上装了git插件
