### ISSUE TITLE
"pipeline编辑"粘贴内容后，保存提示“null”.

### ISSUE THREAD

**Issue by gouxiaodong** [alibaba/intelligent-test-platform#14]
您好，我对您项目的智能化技术很惊喜，想使用一下。
但我是个编程小白，JAVA从没用过，这两天按照您给的教程，磕磕碰碰的到了最后一步（其实不确定前面的步骤是不是正确）。
我在"pipeline编辑"里复制粘贴了“pipeline_demo”内的内容，然后试图保存，结果网页提示“null”，请问这是什么原因呢？  
是因为“数据源编辑”没有输入内容吗？  如果是的话，应该输入什么呢？
期待您的回复，祝好！

**Comment by panjiateng** [comment]
你好，可以尝试在ide上单步debug一下。
数据源编辑可以忽略。

**Comment by nature1995** [comment]
你的数据库可能没有配置正确，检查下密码是否修改了。

**Comment by mokulai** [comment]
我之前出现这个报错是因为数据库表不存在，看下数据库里是否建好需要的表了

**Comment by gouxiaodong** [comment]
@panjiateng @nature1995 @mokulai 感谢各位，我赶紧试一试

**Comment by gouxiaodong** [comment]
感谢各位，问题已经解决，是数据库连接的问题。
一开始报错为：
Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value '?й???????' is unrecognized or represents more than
one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone val
ue if you want to utilize time zone support.
然后试图在url后面添加“?serverTimezone=UTC” ，但是问题仍然存在。随后换一种方式，在mysql命令窗口输入：
mysql> set global time_zone='+8:00';
最终问题得以解决。
再次感谢各位。

**Comment by nature1995** [comment]
时区问题可以在IDE中设置或者在JDBC的url参数后面设置，这个希望开发者可以加上，修复一下。 @panjiateng
