### ISSUE TITLE
Unknown collation: 'utf8mb4_0900_ai_ci'

### ISSUE THREAD

**Issue by piaodangdang** [alibaba/intelligent-test-platform#4]
初始化数据时候报这个错误，是需要使用mysql8吗 ？ 目前我是用的数据库是docker mysql:5.7

**Comment by MissRabbit1993** [comment]
本地安装mysql版本是8.0.19，建议升级版本

**Comment by piaodangdang** [comment]
哦 好的 是否把环境依赖版本在readme中说明一下？

**Comment by panjiateng** [comment]
好的，我们添加下

**Comment by VinceChen0301** [comment]
用utf8mb4_unicode_ci或者utf8mb4_general_ci可以吗？

**Comment by MissRabbit1993** [comment]
保持默认字符集utf8mb4即可，排序字符集区别不影响
