### ISSUE TITLE
部署环境中，多环境的展示有误

### ISSUE THREAD

**Issue by VinceChen0301** [alibaba/intelligent-test-platform#7]
在pipeline的hostList里面添加多个host，然后跳转到部署环境页面，host列表中只展示hostList中最后一个Host。
考虑是EnvsProcessor类下面的findByScenarioId方法里面，在遍历hostList的时候，由于envUnit在循环体外创建，所以循环体内部使用的是同一个envUnit对象，所以最后return这个list的时候，里面只有一个envUnit，只不过属性的值被更新了而已。
建议这里优化一下。

**Comment by panjiateng** [comment]
好的，收到。
由于markog一期未开放环境管理系统和容器部署技术，因此，此处就简单的mock，想让大家更多关注智能化技术等。
后续将持续开源更完善的版本

**Comment by VinceChen0301** [comment]
> 好的，收到。
> 由于markog一期未开放环境管理系统和容器部署技术，因此，此处就简单的mock，想让大家更多关注智能化技术等。
> 后续将持续开源更完善的版本

拿到手上第一反应就是迫不及待想用起来了哈哈
